### ISSUE TITLE
Error: unsupported workflow run event

### ISSUE THREAD

**Issue by dpo** [tonyhallett/artifacts-url-comments#109]
Hi,

I'm getting an `Error: unsupported workflow run event` error message with this action that I'm not understanding. I opened a discussion here: https://github.com/orgs/community/discussions/34117.

Also pinging @veitbjarsch since I use his fork (where issues are disabled).

Thanks in advance!

**Comment by tonyhallett** [comment]
Your discussion has been answered. On my readme see When.

**Comment by veitbjarsch** [comment]
@dpo As far I remember I didn't solved any issue in my branch. I just debugged the and opened an issue here: https://github.com/tonyhallett/artifacts-url-comments/issues/80

So your issue isn't related to my branch exactly.

**Comment by dpo** [comment]
Thank you both. About the "When" section of the README here, I guess I mistakenly thought that `pull_request_target` was a pull request event.

Would it make sense to add `pull_request_target` to the list of supported events?

**Comment by tonyhallett** [comment]
> Would it make sense to add pull_request_target to the list of supported events?

Probably.  It has been some time since I wrote the action and I am no longer familiar.

This is the code that works for pull_request and not pull_request_target
https://github.com/tonyhallett/github-actions/blob/8c897ff1d5a09ab874b195192aca03b1d702b261/src/workflow/workflowGetPullRequest.ts#L31

I am accessing the payload of the triggering

You can access the [workflow_run event payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run) that corresponds to the workflow that triggered your workflow.
```
async function getPullRequestForPullRequestWorkflow(
  octokit: Octokit,
  payload: WorkflowRunEvent
): Promise<PullRequest> {
  const pullState = getPullState()
  const workflowRun = payload.workflow_run // *************************************
  const headBranch = workflowRun.head_branch
  const headSha = workflowRun.head_sha
  const ownerLogin = workflowRun.head_repository.owner.login
  const parameters: PullsListParameters = {
    per_page: 100,
    head: `${ownerLogin}:${headBranch}`,
    state: pullState,
    ...github.context.repo
  }
  const openHeadPulls: Pulls = await octokit.paginate(
    octokit.pulls.list,
    parameters
  )
  return (openHeadPulls.find(
    pull => pull.head.sha === headSha //**********************
  ) as never) as PullRequest
}

```
I expect that the information is available.  Please can you check that this is the case.

Note that github are now demonstrating getting the artificact information from github-script
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
